// User
export const userTypes = {
  LOAD_USER: 'LOAD_USER',
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  ERROR: 'ERROR',
};

// Products
export const productTypes = {
  GET_PRODUCT: 'GET_PRODUCT',
  GET_HOME_PRODUCTS: 'GET_HOME_PRODUCTS',
  GET_SHOP_PRODUCTS: 'GET_SHOP_PRODUCTS',
  LOADING_PRODUCT: 'LOADING_PRODUCT',
};

// Cart
export const cartTypes = {
  LOAD_PRODUCT: 'LOAD_PRODUCT',
  ADD_TO_CART: 'ADD_TO_CART',
  REMOVE_ITEM_CART: 'REMOVE_ITEM_CART',
  CLEAR_CART: 'CLEAR_CART',
  DECREASE_PRODUCT_QUANTITY: 'DECREASE_PRODUCT_QUANTITY',
  SET_LOADING: 'SET_LOADING',
};
